config/routes.rb
Rails.application.routes.draw do
  root 'public#index'

  resources :groups do
    post 'activate', on: :member
  end
  resources :sessions, only: [:create]
  resources :dashboard, only: [:index]

  post '/add_movie/:imdb_id', to: 'movies#add_movie', as: 'add_movie'
  post '/remove_movie/:imdb_id', to: 'movies#remove_movie', as: 'remove_movie'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_movies, dependent: :destroy
  has_many :movies, through: :group_movies
end

app/models/group_movie.rb
class GroupMovie < ApplicationRecord
  belongs_to :group, counter_cache: :movies_count
  belongs_to :movie

  validates :group_id, uniqueness: { scope: :movie_id }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :group_movies, dependent: :destroy
  has_many :groups, through: :group_movies
end

app/models/user.rb
class User < ApplicationRecord
  has_many :groups, dependent: :destroy
  has_many :movies, -> { distinct }, through: :groups
  belongs_to :active_group, class_name: 'Group'

  before_validation -> { build_active_group(name: 'Initial', user: self) }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from AppErrors::NotAuthorizedError do |e|
    respond_to do |format|
      format.html { render_error_page(401) }
      format.json { render_error(e.message, 401) }
    end
  end

  rescue_from ActiveRecord::RecordNotFound, ActionController::UnknownFormat do |e|
    respond_to do |format|
      format.html { render_error_page(404) }
      format.json { render_error(e.message, 404) }
    end
  end

  def authenticate_request
    return true if current_user

    raise AppErrors::NotAuthorizedError, 'Not authenticated'
  end

  def current_user
    @current_user ||= user_id && User.find_by(id: user_id)
  end

  def user_id
    session[:user_id]
  end

  private

  def render_error(msg, status)
    render json: { status: 'error', message: msg }, status:
  end

  def render_error_page(code)
    render file: Rails.root.join("public/#{code}.html").to_s, layout: false, status: code
  end
end

app/controllers/concerns/movie_searchable.rb
module MovieSearchable
  extend ActiveSupport::Concern

  private

  def prepare_movie_searchable_variables
    @term = params[:search]
    @search_movie = @term ? search_movie(@term) : nil
    @movie_imdb_ids = current_user.active_group.movies.pluck(:imdb_id)
  end

  def search_movie(term)
    Rails.cache.fetch("search_movie/#{term}", expires_in: 5.minutes) do
      Omdb::SearchService.call(term)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_request
  include MovieSearchable

  def index
    prepare_movie_searchable_variables
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_request
  before_action :set_group, only: %i[show edit update destroy activate]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show
    @movies = @group.movies
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  def activate
    current_user.update(active_group: @group)

    redirect_to action: :index
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    if @group.user.active_group == @group
      msg = { alert: 'Cannot destroy active group.' }
    else
      @group.destroy
      msg = { notice: 'Group was successfully destroyed.' }
    end

    respond_to do |format|
      format.html { redirect_to groups_url, msg }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = current_user.groups.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_request
  include MovieSearchable

  def add_movie
    movie = add_movie_to_active_group
    async_update_movie_info(movie) if movie
    prepare_movie_searchable_variables
    render 'dashboard_movies'
  end

  def remove_movie
    remove_movie_from_active_group
    prepare_movie_searchable_variables
    render 'dashboard_movies'
  end

  private

  def add_movie_to_active_group
    MovieCommands::AddToGroup.call(params[:imdb_id], current_user.active_group)
  end

  def remove_movie_from_active_group
    MovieCommands::RemoveFromGroup.call(params[:imdb_id], current_user.active_group)
  end

  def async_update_movie_info(movie)
    Thread.new do
      MovieCommands::UpdateMovie.call(movie)
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:user_id] = (params[:user_id].presence || 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # rubocop:disable Rails/HelperInstanceVariable
  def current_user
    @current_user
  end
  # rubocop:enable Rails/HelperInstanceVariable

  def nav_classes(controller, action = nil)
    active = 'block py-2 pl-3 pr-4 rounded text-white bg-blue-700  md:bg-transparent md:text-blue-700 md:p-0'
    inactive = 'block py-2 pl-3 pr-4 rounded text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:border-0
                md:hover:text-blue-700 md:p-0'

    activate = action ? current_page?(controller:, action:) : controller_name == controller
    activate ? active : inactive
  end

  def svg(name)
    file_path = Rails.root.join("app/assets/images/#{name}.svg").to_s
    if File.exist?(file_path)
      File.read(file_path).html_safe
    else
      '(not found)'
    end
  end

  def proper_url?(url)
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def active_group?(group)
    group == current_user.active_group
  end
end

app/views/dashboard/index.html.erb
<div class='mb-5'>
  <h2>Your active group</h2>
  <div id='user-active-group'>
    <%= render partial: 'groups/group', object: current_user.active_group %>
  </div>
</div>

<%= form_tag(dashboard_index_path, method: :get, class: 'max-w-md mt-5') do %>
  <%= label_tag('movie-search', 'Search', class: 'mb-2 text-sm font-medium text-gray-900 sr-only') %>
  <div class="relative">
    <div class="absolute w-10 inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <%= svg 'loupe' %>
    </div>
    <%= search_field_tag('search', nil,
      class: 'block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500',
      id: 'movie-search',
      placeholder: 'Search movie title',
      value:params[:search],
      required: true
    ) %>
    <%= button_tag('Search',
      class: 'text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2'
    ) %>
  </div>
<% end %>

<div id="search-movie-list" class="min-w-full">
  <%= render partial: 'movies/search_movie', collection: @search_movie %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>"
  class="block relative md:w-80 my-5 break-after-column p-6 border border-gray-200 rounded-lg shadow hover:bg-gray-100"
>
  <% if active_group?(group) %>
    <div class='w-4 h-auto absolute top-1 left-1'>
      <%= svg 'check_box' %>
    </div>
  <% end %>

  <p class="m-3 tracking-tight text-gray-900">
    <strong class="text-bold font-medium">Name:</strong>
    <%= group.name %>
  </p>

  <p class="m-3 tracking-tight text-gray-900">
    <strong class="block text-bold font-medium mb-1">Description:</strong>
    <%= group.description %>
  </p>

  <p class="m-3">
    <strong class="block font-medium mb-1">Movies:</strong>
    <%= group.movies_count %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show", group, data: { 'turbo-frame': "_top" }, class: "rounded-lg py-2 px-4 bg-gray-300 inline-block font-small hover:bg-gray-400" %>
    <%= link_to 'Change', edit_group_path(group), data: { 'turbo-frame': "_top" }, class: "rounded-lg py-2 px-4 bg-gray-300 inline-block font-small hover:bg-gray-400" %>
    <% unless active_group?(group) %>
      <%= button_to 'Activate', activate_group_path(group),
        class: "rounded-lg py-2 px-4 font-small bg-gray-300 hover:bg-gray-400",
        form_class: 'inline-block'
      %>
    <% end %>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Show this group", @group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= current_user.name %>'s Groups</h1>
    <%= link_to 'New group', new_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="groups" class="mt-5 min-w-full md:grid md:grid-cols-2 md:justify-items-center">
    <%= render @groups %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>

  <%= render "form", group: @group %>

  <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @group %>

    <%= link_to 'Edit this group', edit_group_path(@group), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this group', group_path(@group), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>
<div class='mx-auto my-4 w-full block'>
  <h2 class="font-bold text-xl">
    Movies
  </h2>
  <div class='mt-5 min-w-full lg:grid lg:grid-cols-3 lg:justify-items-center'>
    <%= render @movies %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="py-2 border-b">
      <div class="flex justify-between">
        <%= render partial: "shared/nav" %>
      </div>
    </header>
    <section class="flashes">
      <%= render partial: "shared/flash" %>
    </section>

    <main class="container mx-auto mt-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>"
  class="block relative lg:w-80 my-5 break-after-column p-6 border border-gray-200 rounded-lg shadow hover:bg-gray-100"
>

  <% if proper_url?(movie.poster) %>
    <%= image_tag(movie.poster, size: 150, class: 'my-5 lg:mx-auto') %>
  <% else %>
    <%= image_tag("blank", size: 150, class: 'my-5') %>
  <% end %>

  <p class="m-3 tracking-tight text-gray-900">
    <strong class="text-bold font-medium">Title:</strong>
    <%= movie.title %>
  </p>

  <p class="m-3 tracking-tight text-gray-900">
    <strong class="text-bold font-medium">Year:</strong>
    <%= movie.year %>
  </p>

  <p class="m-3 tracking-tight text-gray-900">
    <strong class="text-bold font-medium">Plot:</strong>
    <%= movie.plot %>
  </p>

  <p class="m-3 tracking-tight text-gray-900">
    <strong class="text-bold font-medium">Type:</strong>
    <%= movie.movie_type %>
  </p>
</div>

app/views/movies/_search_movie.html.erb
<% in_active_group = @movie_imdb_ids.include?(search_movie.imdbID) %>
<% cache [ search_movie.imdbID, in_active_group ] do %>
  <div id="<%= search_movie.imdbID %>" class='grid grid-cols-3 gap-4 border-black border-solid'>
    <% if proper_url?(search_movie.Poster) %>
      <%= image_tag(search_movie.Poster, size: 150, class: 'my-5') %>
    <% else %>
      <%= image_tag("blank", size: 150, class: 'my-5') %>
    <% end %>

    <div>
      <p class="my-3">
        <strong class="block font-medium mb-1">In collection:</strong>
        <% if in_active_group %>
          <div class='w-4 h-auto'>
            <%= svg 'check_box' %>
          </div>
        <% else %>
          No
        <% end %>
      </p>

      <p class="my-3">
        <strong class="block font-medium mb-1">Title:</strong>
        <%= search_movie.Title %>
      </p>

      <p class="my-3">
        <strong class="block font-medium mb-1">Year:</strong>
        <%= search_movie.Year %>
      </p>

      <p class="my-3">
        <strong class="block font-medium mb-1">Type:</strong>
        <%= search_movie.Type %>
      </p>
    </div>

    <div class='flex items-center justify-center'>
      <% unless in_active_group %>
        <%= button_to('Add to active group', add_movie_path(search_movie.imdbID), params: { search: @term, anchor: search_movie.imdbID  },
          class: 'text-white right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2'
        ) %>
      <% else %>
        <%= button_to('Remove from active group', remove_movie_path(search_movie.imdbID), params: { search: @term, anchor: search_movie.imdbID  },
          class: 'text-white right-2.5 bottom-2.5 bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2'
        ) %>
      <% end %>
    </div>
  </div>
  <hr class="my-12 h-0.5 border-t-2 bg-neutral-600 opacity-100" />
<% end %>

app/views/movies/dashboard_movies.turbo_stream.erb
<%= turbo_stream.update 'search-movie-list' do %>
  <%= render partial: 'movies/search_movie', collection: @search_movie %>
<% end %>

<%= turbo_stream.update 'user-active-group' do %>
  <%= render partial: 'groups/group', object: current_user.active_group %>
<% end %>

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <div class="bg-green-100 rounded-lg py-5 px-6 mb-4 text-base text-green-700 mb-3" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="bg-red-100 rounded-lg py-5 px-6 mb-4 text-base text-red-700 mb-3" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<%= link_to "Movies", "/", class: "text-2xl font-bold mt-4 block uppercase pl-6 text-slate-700" %>

<nav class="bg-white border-gray-200">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>

    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white">
        <li>
          <%= link_to 'Dashboard', dashboard_index_path,
            class: nav_classes('dashboard')
          %>
        </li>
        <li>
          <%= link_to "Groups", groups_path,
            class: nav_classes('groups')
          %>
        </li>
        <li>
          <div data-controller='select' class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0"">
            <%= label(:user, :name, 'Select User', class: 'w-full mb-2 text-gray-900') %>
            <%= select(:user, :name, User.all.collect {|p| [ p.name, p.id ] }, { prompt: 'select user', selected: session[:user_id] },
              class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
                focus:border-blue-500 block w-full p-2.5',
              data: { action: 'select#change' }
              )
            %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>